blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/', views.PostIndexView.as_view(), name='post_index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create', views.post_edit_view, name='post_create'),
    path('posts/<int:pk>/edit', views.post_edit_view, name='post_edit'),
    path('posts/<int:pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:pk>/comments', views.PostCommentIndexView.as_view(), name='post_comment_index'),
    path('posts/<int:pk>/comments/new', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<int:pk>/edit', views.CommentEditView.as_view(), name='comment_edit'),
    path('comments/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/<int:pk>/vote', views.comment_vote, name='comment_vote'),
    path('authors/<slug:slug>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('users/<slug:slug>/edit', views.user_edit_view, name='user_edit'),
    path('users/<slug:slug>/delete', views.UserDeleteView.as_view(), name='user_delete'),
    path('users/<slug:slug>/', views.UserDetailView.as_view(), name='user_detail'),
    #path('notifications/', views.NotificationIndexView.as_view(), name='notification_index'),
   # path('notifications/<int:pk>/delete', views.NotificationDeleteView.as_view(), name='notification_delete'),
    path('tags/', views.TagIndexView.as_view(), name='tag_index'),
    path('tags/<slug:slug>/', views.TagDetailView.as_view(), name='tag_detail'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('notifications/', include('notifications.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='/blog/posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from . import views

app_name='notifications'
urlpatterns = [
    path('', views.NotificationIndexView.as_view(), name='notification_index'),
    path('<int:pk>/delete', views.NotificationDeleteView.as_view(), name='notification_delete'),
    path('messages/', views.PrivateMessageIndexView.as_view(), name='privatemessage_index'),
    path('messages/<int:pk>', views.PrivateMessageUserDetailView.as_view(), name='privatemessage_user_detail'),
    path('messages/system', views.PrivateMessageUserDetailView.as_view(), name='privatemessage_system_detail'),
    path('messages/<int:pk>/create', views.PrivateMessageCreateView.as_view(), name='privatemessage_create'),
    path('messages/<int:pk>/delete', views.PrivateMessageDeleteView.as_view(), name='privatemessage_delete'),
]

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import Author, Post
from PIL import Image
from django.contrib.humanize.templatetags.humanize import intcomma
from accounts.forms import BaseUserForm
from django.utils.translation import gettext as _

class UserSettingsForm(BaseUserForm):
    password = forms.CharField(max_length=User.password.field.max_length, required=False)
    confirm_password = forms.CharField(max_length=User.password.field.max_length, required=False)
    current_password = forms.CharField(max_length=User.password.field.max_length, required=False)
    
    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise AttributeError('User cannot be None')
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        current_password = self.cleaned_data.get('current_password')
        email = self.cleaned_data.get('email')

        if password or email != self.user.email:
            if not current_password:
                self.add_error('current_password', _('Required to change username or password'))
            elif not authenticate(username=self.user.username, password=current_password):
                self.add_error('current_password', _('Password is incorrect'))

class AuthorSettingsForm(forms.ModelForm):
    author_enabled = forms.BooleanField(required=False)
    moderator = forms.BooleanField(required=False)

    class Meta:
        model = Author
        fields = ['bio']

class PostForm(forms.ModelForm):
    tags = forms.CharField(max_length=255, required=False)
    remove_header_image = forms.BooleanField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'header_image', 'content']

    def clean(self):
        super().clean()
        header_image_file = self.cleaned_data.get('header_image')
        if header_image_file:
            with Image.open(header_image_file) as im:
                total_pixels = im.width * im.height
                if total_pixels > 40000000:
                    self.add_error('header_image', f'Image size ({intcomma(total_pixels)} pixels) exceeds limit of 10,000,000 pixels')

blog/views.py
from django.contrib.auth.models import User
from notifications.models import NotificationType
from django.http.response import HttpResponseRedirect, JsonResponse
from django.http import Http404
from django.urls.base import reverse
from blog.forms import AuthorSettingsForm, UserSettingsForm, PostForm
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.views import View
from .models import Post, Author, Comment, Tag
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.defaultfilters import slugify
from PIL import Image
from os.path import join, exists
from os import remove
from django.db.models import Count, F, Q
from .templatetags.blog_filters import compact_int
from django.contrib.auth.password_validation import password_changed
from django.conf import settings
# Create your views here.

class PostIndexView(ListView):
    model = Post
    paginate_by = 20
    queryset = Post.objects.filter(author__visible=True)

class PostDetailView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk, author__visible=True)
        comments = post.comment_set.order_by('-votes')[:5]
        return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'comment_count': post.comment_set.count()})

class PostCommentIndexView(ListView):
    paginate_by = 20
    template_name = 'blog/post_comment_index.html'
    context_object_name = 'comments'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['post'] = self.post
        context['sort_by'] = self.sort_by
        return context

    def get_queryset(self):
        self.post = get_object_or_404(Post, pk=self.kwargs['pk'], author__visible=True)
        self.sort_by = 'top'
        if 'sort' in self.request.GET:
            sort = self.request.GET['sort']
            if sort == 'recent':
                self.sort_by = 'recent'
                return self.post.comment_set.order_by('-created_on').all()
        return self.post.comment_set.order_by('-votes')

class AuthorDetailView(ListView):
    paginate_by = 20
    template_name = 'blog/author_detail.html'

    def get_queryset(self):
        self.author = get_object_or_404(Author.objects.filter(visible=True), slug=self.kwargs['slug'])
        return self.author.post_set.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        return context

#TODO Only check user_form.isvalid() if can_user_edit is true
@login_required
def user_edit_view(request, slug):
    
    author = get_object_or_404(Author, slug=slug)
    can_edit_user = request.user == author.user
    can_edit_author = author.can_user_edit(request.user)
    saved = False
    if not can_edit_user and not can_edit_author:
        raise PermissionDenied
    if request.method == 'POST':
        user_form = UserSettingsForm(request.POST, user=author.user)
        author_form = AuthorSettingsForm(request.POST)
        if user_form.is_valid() and author_form.is_valid():
            saved = True
            password = user_form.cleaned_data.get('password')
            email = user_form.cleaned_data.get('email')
            if can_edit_user:
                author.user.email = email
                if password:
                    author.user.set_password(password)
                    password_changed(password, user=author.user)
            if can_edit_author:
                author.bio = author_form.cleaned_data.get('bio')

                if author.user != request.user:
                    author.set_author(author_form.cleaned_data['author_enabled'])
                    
                if author.user != request.user and request.user.is_staff:
                    author.set_moderator(author_form.cleaned_data['moderator'])
                author.save()
            author.user.save()
            
            if request.user == author.user:
                login(request, author.user) #Changing a users password logs them out   
    else:
       user_form = UserSettingsForm(user=author.user, initial={'email': author.user.email})
       author_form = AuthorSettingsForm(initial={'author_enabled': author.visible, 'moderator': author.user.has_perm('blog.edit_author'), 'bio': author.bio})

    context = {
        'user_form': user_form, 
        'author_form': author_form, 
        'author': author, 
        'saved': saved,
        'can_edit_author': can_edit_author,
        'can_edit_user': can_edit_user,
    }

    return render(request, 'blog/user_edit.html', context)

@login_required
def post_edit_view(request, pk=None):
    post = get_object_or_404(Post, pk=pk, author__visible=True) if pk else None
    if (post and not post.can_user_edit(request.user)) or (not post and not Post.can_user_create(request.user)):
        raise PermissionDenied
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            if not post:
                post = Post(author=request.user.author)
            post.title = form.cleaned_data.get('title')
            post.content = form.cleaned_data.get('content')
            post.save()
            header_image = form.cleaned_data.get('header_image')
            if header_image and not getattr(settings, 'DISABLE_IMAGE_UPLOADS', False):
                
                post.header_image_name = header_image.name
                with Image.open(header_image) as im:
                    post.header_image = join(Post.header_image.field.upload_to, f'header_image_post_{post.pk}.jpeg')
                    image = Image.new('RGB', (im.width, im.height))
                    image.putdata(im.getdata())
                    image.save(post.header_image.path)
                    post.save()
            elif form.cleaned_data.get('remove_header_image', False):
                if exists(post.header_image.path):
                    remove(post.header_image.path)
                post.header_image = None
                post.header_image_name = None
                post.save()

            post.tags.clear()
            for tag_name in form.cleaned_data.get('tags', '').lower().split(','):
                if tag_name.strip():
                    try:
                        tag = Tag.objects.get(slug=slugify(tag_name.strip()))
                    except Tag.DoesNotExist:
                        tag = Tag()
                    tag.name = tag_name.strip()
                    tag.save()
                    post.tags.add(tag)
            post.save()
            return HttpResponseRedirect(reverse('blog:post_detail', kwargs={'pk': post.pk}))
    else:
        form = PostForm(instance=post, initial={'tags': post.tags_str() if post else ''})
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post, 'images_disabled': getattr(settings, 'DISABLE_IMAGE_UPLOADS', False)})

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post

    def test_func(self):
        return self.get_object().can_user_delete(self.request.user)

    def get_success_url(self, *args, **kwargs):
        return reverse('blog:author_detail', kwargs={'slug': self.get_object().author.slug})

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['text']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        context['next'] = self.request.GET.get('next', None)
        return context

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        comment = Comment(post=post, commenter=self.request.user, text=form.cleaned_data['text'])
        comment.save()
        if post.author.user != self.request.user:
            post.author.user.notification_set.create(content=comment, type=NotificationType.get(name='new_comment_on_post'))
        next = self.request.POST.get('next', None)
        return HttpResponseRedirect(next if next else '/')

class CommentEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['text']

    def test_func(self):
        return self.get_object().can_user_edit(self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['post'] = self.get_object().post
        context['next'] = self.request.GET.get('next', None)
        return context

    def form_valid(self, form):
        comment = self.get_object()
        comment.text=form.cleaned_data['text']
        comment.save()
        next = self.request.POST.get('next', None)
        return HttpResponseRedirect(next if next else '/')

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next', None)
        return context

    def test_func(self):
        return self.get_object().can_user_delete(self.request.user)

    def get_success_url(self, *args, **kwargs):
        next = self.request.POST.get('next', None)
        return next if next else '/'

class UserDetailView(ListView):
    paginate_by = 20
    template_name = 'blog/user_detail.html'
    context_object_name = 'comments'

    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['profile_user'] = self.user
        return context

    def get_queryset(self):

blog/templates/blog/base/comment_base.html
{% load blog_filters %}
{% load blog_tags %}
<li>
    <div class="comment border d-flex">
        <div class="comment-votes-container">
            {% if request.user.is_authenticated and request.user != comment.commenter %}
                <form method="POST" action="{% url 'blog:comment_vote' comment.id %}" id="comment-{{comment.id}}-upvote-form" class="comment-upvote-form" data-id="{{comment.id}}">
                    {% csrf_token %}
                    <input type="hidden" name="type" value="upvote">
                    <input type="hidden" name="next" value="{{ request.get_full_path }}">
                    <button class="btn-blank">
                        <i id="{{comment.id}}-icon-u" class="bi bi-arrow-up-square{% if comment|upvoted:request.user %}-fill{% endif %}"></i>
                    </button>
                </form>
            {% else %}
                <i class="bi bi-arrow-up-square vote-disabled"></i>
            {% endif %}
            <span id="comment-{{comment.id}}-votes" data-votes="{{ comment.votes }}">{{comment.votes|intcompact}}</span>
            {% if request.user.is_authenticated and request.user != comment.commenter %}
            <form method="POST" action="{% url 'blog:comment_vote' comment.id %}" id="comment-{{comment.id}}-downvote-form" class="comment-downvote-form" data-id="{{comment.id}}">
                {% csrf_token %}
                <input type="hidden" name="type" value="downvote">
                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                <button class="btn-blank">
                    <i id="{{comment.id}}-icon-d" class="bi bi-arrow-down-square{% if comment|downvoted:request.user %}-fill{% endif %}"></i>
                </button>
            </form>
            {% else %}
                <i class="bi bi-arrow-down-square vote-disabled"></i>
            {% endif %}
        </div>
        <div>
            <div class="comment-header">
                By <a href="{% url 'blog:user_detail' comment.commenter.author.slug %}">{{comment.commenter.username}}</a> on {{comment.created_on}}
                <span>
                    {% if user|can_edit:comment %}<a href="{% url 'blog:comment_edit' comment.pk %}?next={{ request.get_full_path|urlencode }}">Edit</a>{% endif %}
                    {% if user|can_delete:comment %}<a href="{% url 'blog:comment_delete' comment.pk %}?next={{ request.get_full_path|urlencode }}"> Delete</a>{% endif %}
                </span>
            </div>
            <div class="comment-text">
                {% markdown comment.text %}
            </div>
            
        </div>
    </div>
</li>

blog/templates/blog/base/page_base.html
{% load static %}
{% load blog_filters %}
{% load blog_tags %}
{% load notification_tags %}
{% url 'blog:post_index' as post_index %}
{% url 'blog:tag_index' as tag_index %}
{% url 'blog:post_create' as post_create %}
{% get_unread_notification_count user as unread_notification_count %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}{% endblock title %} - Blog
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link href="{% static 'blog/style.css' %}" rel="stylesheet">
        
        
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/markdown-it/12.0.6/markdown-it.min.js" integrity="sha512-7U8vY7c6UQpBNQOnBg3xKX502NAckvk70H1nWvh6W7izA489jEz+RCN3ntT1VMdXewaSKkOrEBegp/h6SPXrjw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="{% static 'blog/js/comments.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'blog/js/markdown.js' %}" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
        

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-xxl">
                <a class="navbar-brand" href="/">Django Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link{% if request.path == post_index %} active{% endif %}" href="{{post_index}}">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if request.path == tag_index %} active{% endif %}" href="{{tag_index}}">Tags</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        <li class="nav-item">
                            {% if user.is_authenticated and user|can_create:'Post' and user.author.visible %}
                                <li class="nav-item">
                                    <a class="nav-link{% if request.path == post_create %} active{% endif %}" href="{% url 'blog:post_create' %}">New post</a>
                                </li>
                            {% endif %}
                        </li>
                        <li class="nav-item dropdown ms-auto">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.is_authenticated %}
                                    {{user.username}} 
                                    {% if unread_notification_count %}<span class="badge rounded-pill bg-primary">{{unread_notification_count}}</span>{% endif %}
                                {% else %}
                                    Login / Signup
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                {% if user.is_authenticated %}
                                    
                                    {% if user.author.visible %}
                                        <li><a class="dropdown-item" href="{% url 'blog:author_detail' slug=user.author.slug %}">Blog</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'blog:user_detail' slug=user.author.slug %}">Profile</a></li>
                                    <li class="clearfix">
                                        <a class="dropdown-item clearfix" href="{% url 'notifications:notification_index' %}">
                                            Notifications
                                            {% if unread_notification_count %}
                                                <span class="badge rounded-pill bg-primary ms-2">{{unread_notification_count}}</span>
                                            {% endif %}
                                        </a>
                                        
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'notifications:privatemessage_index' %}">Messages</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'blog:user_edit' slug=user.author.slug %}">Settings</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}?next={{request.get_full_path|urlencode}}">Logout</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'login' %}?next={{request.get_full_path|urlencode}}">Login</a></li>
                                    <li><a class="dropdown-item" href="{% url 'signup' %}?next={{request.get_full_path|urlencode}}">Signup</a></li>
                                {% endif %}
                            </ul>
                          </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-xxl">
        {% block content %}
            
        {% endblock content %}
        </div>
    </body>
</html>
    
    

blog/templates/blog/base/pagination_base.html
{% if is_paginated %}
{% load blog_tags %}
{% format_pages 3 as pages%}
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="{% current_url 'page' page_obj.previous_page_number %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    
    {% for page in pages %}
        {% if page == '...' %}
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
        {% else %}
        <li class="page-item{% if page == page_obj.number %} active{% endif %}">
            <a class="page-link" href="{% current_url 'page' page %}">{{ page }}</a>
        </li>
        {% endif %}
    {% endfor %}
    
    {% if page_obj.has_next %}
    <li class="page-item" aria-label="Next">
        <a class="page-link" href="{% current_url 'page' page_obj.next_page_number %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% else %}
    <li class="page-item disabled" aria-label="Next">
        <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
    
</ul> 
{% endif %}
    

blog/templates/blog/base/post_list_base.html
<div class="post-card-list">
    {% if post_list %}
        {% for post in post_list %}
        <div class="card post-card">
            <div {% if post.header_image %}style="background-image: url('{{ post.header_image.url }}');"{% endif %} class="card-img-top post-card-image"></div>
            <div>
                <div class="card-body">
                
                <h5 class="card-title post-card-title">
                    <a href="{{post.get_absolute_url}}">{{post.title|truncatechars:25}}</a>
                </h5>
                <span class="card-subtitle mb-2 text-muted">
                    By <a href="{{post.author.get_absolute_url}}">{{post.author.user.username}}</a>
                </span>
                <div class="card-text">{{post.content|truncatechars:100}}</div>
                </div>
            </div>
        </div>
        {% endfor %}
        
        {% include 'blog/base/pagination_base.html' %}

    {% else %}
        <div class="text-muted text-center mt-2">No posts yet</div>
    {% endif %}
 </div>