blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/', views.PostIndexView.as_view(), name='post_index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create', views.post_edit_view, name='post_create'),
    path('posts/<int:pk>/edit', views.post_edit_view, name='post_edit'),
    path('posts/<int:pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:pk>/comments', views.PostCommentIndexView.as_view(), name='post_comment_index'),
    path('posts/<int:pk>/comments/new', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<int:pk>/edit', views.CommentEditView.as_view(), name='comment_edit'),
    path('comments/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/<int:pk>/vote', views.comment_vote, name='comment_vote'),
    path('authors/<slug:slug>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('users/<slug:slug>/edit', views.user_edit_view, name='user_edit'),
    path('users/<slug:slug>/delete', views.UserDeleteView.as_view(), name='user_delete'),
    path('users/<slug:slug>/', views.UserDetailView.as_view(), name='user_detail'),
    #path('notifications/', views.NotificationIndexView.as_view(), name='notification_index'),
   # path('notifications/<int:pk>/delete', views.NotificationDeleteView.as_view(), name='notification_delete'),
    path('tags/', views.TagIndexView.as_view(), name='tag_index'),
    path('tags/<slug:slug>/', views.TagDetailView.as_view(), name='tag_detail'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('notifications/', include('notifications.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='/blog/posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from . import views

app_name='notifications'
urlpatterns = [
    path('', views.NotificationIndexView.as_view(), name='notification_index'),
    path('<int:pk>/delete', views.NotificationDeleteView.as_view(), name='notification_delete'),
    path('messages/', views.PrivateMessageIndexView.as_view(), name='privatemessage_index'),
    path('messages/<int:pk>', views.PrivateMessageUserDetailView.as_view(), name='privatemessage_user_detail'),
    path('messages/system', views.PrivateMessageUserDetailView.as_view(), name='privatemessage_system_detail'),
    path('messages/<int:pk>/create', views.PrivateMessageCreateView.as_view(), name='privatemessage_create'),
    path('messages/<int:pk>/delete', views.PrivateMessageDeleteView.as_view(), name='privatemessage_delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import Permission, User, Group
from django.db.models.deletion import CASCADE
from django.db.models.signals import post_save, post_init, pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify, truncatechars
from django.urls import reverse
from os.path import basename
from .util import create_group_if_not_exists
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.conf import settings

class Post(models.Model):
    
    title = models.CharField(max_length=255)
    header_image = models.ImageField(null=True, blank=True, upload_to='blog_post_header_images/')
    header_image_name = models.CharField(null=True, blank=True, max_length=header_image.max_length)
    content = models.TextField(max_length=50000)
    tags = models.ManyToManyField('Tag')
    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']
        permissions = [
            ("create_own_post", "Can create a new post with themselves as the author"),
        ]

    @staticmethod
    def can_user_create(user):
        return (user.has_perm('blog.create_own_post') and user.author.visible)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def has_been_edited(self):
        return (self.updated_on - self.created_on).total_seconds() > 60

    def can_user_edit(self, user):
        return self.author == user.author or user.has_perm('blog.edit_post')

    def can_user_delete(self, user):
        return self.author == user.author or user.has_perm('blog.delete_post')

    def tags_str(self):
        return ', '.join([tag.__str__() for tag in self.tags.all()])

    def get_header_image_file_name(self):
        if self.header_image_name and self.header_image:
            return basename(self.header_image_name)
        elif self.header_image:
            return basename(self.header_image.name)
        else:
            return None

    def __str__(self):
        return truncatechars(self.title, 100)

class Comment(models.Model):
    commenter = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    votes = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = [
            ("delete_comments_on_own_post", "Can delete any comment left on a post they created"),
        ]
        
    class NotificationsMeta:
        notifications = [
            ('new_comment_on_post', 'New reply to post', 'When someone submits a comment one of your posts')
        ]

    def can_user_edit(self, user):
        return self.commenter == user or user.has_perm('blog.change_comment')

    def can_user_delete(self, user):
        return self.commenter == user or user.has_perm('blog.delete_comment') or self.post.author == user.author

    """Calculate vote totals"""
    def get_computed_votes(self):
        if not getattr(self, 'cached_votes', None):
            self.cached_votes = self.commentvote_set.filter(type='u').count() - self.commentvote_set.filter(type='d').count()
        return self.cached_votes
        #return -1234

    def has_voted(self, user, type):
        return self.commentvote_set.filter(user=user, type=type).exists()

    def __str__(self):
        return f'{self.commenter}: {truncatechars(self.text, 100)}'

class CommentVote(models.Model):

    VOTE_TYPE = (
        ('u', 'Upvote'),
        ('d', 'Downvote'),
    )
    type = models.CharField(max_length=1, choices=VOTE_TYPE, blank=True, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Author(models.Model):
    AUTHOR_PERMS = ['modify_own_author', 'create_own_post', 'delete_comments_on_own_post']
    MOD_PERMS = ['delete_comment', 'delete_post', 'change_author', 'delete_user']
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
    slug = models.SlugField(unique=True)
    bio = models.TextField(max_length=500, null=True, blank=True)
    visible = models.BooleanField(default=False)

    class Meta:
        permissions = [
            ("modify_own_author", "Can change their own author settings and visibilty status"),
        ]

    def set_author(self, is_author):
        group = create_group_if_not_exists('author', Author.AUTHOR_PERMS)
        if is_author:
            self.user.groups.add(group)
        else:
            self.user.groups.remove(group)
        self.visible = is_author

    def set_moderator(self, is_moderator):
        create_group_if_not_exists('mod', Author.MOD_PERMS)
        if is_moderator:
            self.user.groups.add(Group.objects.get(name='mod'))
        else:
            self.user.groups.remove(Group.objects.get(name='mod'))

    def can_user_edit(self, user):
        return user.has_perm('blog.change_author') or (user == self.user and user.has_perm('blog.modify_own_author')) or user.is_staff

    def can_user_delete(self, user):
        return user.has_perm('auth.delete_user') or user == self.user

    def get_absolute_url(self):
        return reverse('blog:author_detail', kwargs={'slug': self.slug})

    @receiver(post_save, sender=User)
    def create_user_author(sender, instance, created, **kwargs):
        if created:
            instance.author = Author.objects.create(user=instance, slug=slugify(instance.username))
            if getattr(settings, 'AUTHOR_DEFAULT', False) == True:
                instance.author.set_author(True)
                instance.author.save()

    @receiver(post_save, sender=User)
    def save_user_author(sender, instance, created, **kwargs):
        instance.author.save()

    def __str__(self):
        return self.user.username

class Tag(models.Model):
    slug = models.SlugField(unique=True, null=True, blank=True)
    name = models.CharField(max_length=50, unique=True)

    @receiver(pre_save, sender='blog.Tag')
    def save_tag(sender, instance, **kwargs):
        instance.slug = slugify(instance.name)

    def __str__(self):
        return self.name
        

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import Author, Post
from PIL import Image
from django.contrib.humanize.templatetags.humanize import intcomma
from accounts.forms import BaseUserForm
from django.utils.translation import gettext as _

class UserSettingsForm(BaseUserForm):
    password = forms.CharField(max_length=User.password.field.max_length, required=False)
    confirm_password = forms.CharField(max_length=User.password.field.max_length, required=False)
    current_password = forms.CharField(max_length=User.password.field.max_length, required=False)
    
    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise AttributeError('User cannot be None')
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        current_password = self.cleaned_data.get('current_password')
        email = self.cleaned_data.get('email')

        if password or email != self.user.email:
            if not current_password:
                self.add_error('current_password', _('Required to change username or password'))
            elif not authenticate(username=self.user.username, password=current_password):
                self.add_error('current_password', _('Password is incorrect'))

class AuthorSettingsForm(forms.ModelForm):
    author_enabled = forms.BooleanField(required=False)
    moderator = forms.BooleanField(required=False)

    class Meta:
        model = Author
        fields = ['bio']

class PostForm(forms.ModelForm):
    tags = forms.CharField(max_length=255, required=False)
    remove_header_image = forms.BooleanField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'header_image', 'content']

    def clean(self):
        super().clean()
        header_image_file = self.cleaned_data.get('header_image')
        if header_image_file:
            with Image.open(header_image_file) as im:
                total_pixels = im.width * im.height
                if total_pixels > 40000000:
                    self.add_error('header_image', f'Image size ({intcomma(total_pixels)} pixels) exceeds limit of 10,000,000 pixels')

blog/templates/blog/author_detail.html
{% extends 'blog/base/page_base.html' %}
{% load blog_filters %}
{% block title %}
    {{author.user.username}}
{% endblock title %}

{% block content %}
    <div class="">
        <div class="clearfix mb-2 mt-2">
            <h3 class="d-inline">{{author.user.username}}</h3>
            <span class="user-controls float-end">
                {% if user|can_edit:author %}
                    <a class="btn btn-primary" href="{% url 'blog:user_edit' author.slug %}">Edit</a>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'blog:user_detail' author.slug %}">View profile</a>
                
            </span>
        </div>
        
        {% if author.bio %}{{author.bio}}{% endif %}
    </div>
    {% include 'blog/base/post_list_base.html' %}
{% endblock content %}

blog/templates/blog/comment_confirm_delete.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    Delete - {{comment.text}}
{% endblock title %}

{% block content %}
    <div>
        <div class="mt-2">
            {% include 'blog/base/comment_base.html'%}
        </div>
        <span class="float-end">
            
            <form method="post" action="{% url 'blog:comment_delete' comment.id %}">
                {% csrf_token %}
                {% if next %}<input type="hidden" name="next" value="{{ next|urlencode }}" />{% endif %}
                
                <input type="submit" class="btn btn-danger" value="Delete">
                <a class="btn btn-primary" href="{{ next|urlencode }}">Cancel</a>
            </form>
            
        </span>
    </div>   
{% endblock content %}

blog/templates/blog/comment_form.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    {% if comment %}Edit{% else %}Submit{% endif %} comment - {{post.title}}
{% endblock title %}
    
{% block content %}
<div class="form-window form-window-wide">
    <form method="post" >
        {% csrf_token %}
        {% if next %}<input type="hidden" name="next" value="{{ next|urlencode }}" />{% endif %}
        <div class="mb-3">
            <label class="form-label" for="{{form.text.name}}">
                {% if comment %} Update your {% else %} Enter a {% endif %}
                comment for <a href="{% url 'blog:author_detail' post.author.slug %}">{{post.author.user.username}}'s</a> post: 
                <a href="{% url 'blog:post_detail' post.pk %}">{{post.title}}</a>
            </label>
            <textarea id="content" rows="10" class="form-control{%if form.text.errors%} is-invalid{%endif%} markdown-editor" aria-label="With textarea" name="{{form.text.name}}">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
            <div class="form-text">Format with markdown</div>
            <div class="invalid-feedback">
                {% for error in form.text.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        <div class="mb-2">
            <div id="content-preview" class="border p-2"></div>
        </div>
        <div>
            <button type="submit" class="btn btn-primary float-end">{% if comment %}Edit{% else %}Submit{% endif %}</button>
        </div>
    </form>
</div>
{% endblock content %}
    

blog/templates/blog/notification_confirm_delete.html
{% extends 'blog/base/page_base.html' %}
{% load notification_tags %}

{% block title %}
    Notification - Delete
{% endblock title %}

{% block content %}
    <div>
        <div>
            {% inline_notification notification %}
        </div>
        <span class="float-end">
            
            <form method="post" action="{% url 'blog:notification_delete' notification.id %}">
                {% csrf_token %}
                {% if next %}<input type="hidden" name="next" value="{{ next|urlencode }}" />{% endif %}
                
                <input type="submit" class="btn btn-danger" value="Delete">
                <a class="btn btn-primary" href="{% if next %}{{ next|urlencode }}{% else %}{% url 'blog:notification_index' %}{% endif %}">Cancel</a>
            </form>
            
        </span>
    </div>   
{% endblock content %}

blog/templates/blog/notification_index.html
{% extends 'blog/base/page_base.html' %}
{% load notification_tags %}

{% block title %}
    Notifications
{% endblock title %}

{% block content %}
    <div class="row">
    <div class="col-md-auto">
        <div class="mb-2 mt-2">
            <form method="GET">
                <h4>Filters</h4>
                {% for notificationtype in notificationtype_list %}
                    <div>
                        <input type="checkbox" id="{{notificationtype.name}}" name="{{notificationtype.name}}" {% if notificationtype in included_notificationtypes %}checked{% endif %}>
                        <label for="{{notificationtype.name}}">{{notificationtype.label}}</label>

                    </div>
                {% endfor %}
                <div class="mt-2 clearfix">
                    <button class="btn btn-primary float-end" type="submit">Apply</button>
                </div>
                
            </form>
        </div>
    </div>
    <div class="col">
        <div class="notification-container mt-2">
            {% if notification_list %}
                <ul class="list-group">
                    {% for notification in notification_list %}
                        <li class="list-group-item">{% inline_notification notification %}</li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="text-muted text-center">No notifications</div>
            {% endif %}
        </div>
        <div class="mt-2">
            {% include 'blog/base/pagination_base.html' %}
        </div>
    </div>
    </div>
{% endblock content %}

blog/templates/blog/post_comment_index.html
{% extends 'blog/base/page_base.html' %}
{% load blog_tags %}

{% block title %}
    {{post.title}} - Comments
{% endblock title %}

{% block content %}
    <div class="clearfix mb-2 mt-2">
        <h3 class="post-comments-header"><a href="{% url 'blog:post_detail' post.pk %}">{{post.title}}</a></h3>
        <div class="mt-2">
            <h3 class="d-inline mt-2">All Comments</h3>
            <span class="user-controls float-end">
                {% if user.is_authenticated %}
                    <a class="btn btn-primary" href="{% url 'blog:comment_create' post.id %}">Leave a comment</a>
                {% endif %}
                <div class="btn-group">
                    <a href="{% current_url 'sort' 'top' %}" class="btn btn-primary{% if sort_by == 'top' %} active {% endif %}" aria-current="page">Top</a>
                    <a href="{% current_url 'sort' 'recent' %}" class="btn btn-primary{% if sort_by == 'recent' %} active {% endif %}" aria-current="page">Recent</a>
                  </div>
            </span>
        </div>
    </div>
    <ul class='comments-list'>
        {% if comments %}
            {% for comment in comments %}
                {% include 'blog/base/comment_base.html'%}
            {% endfor %}
        {% endif %} 
    </ul>
    {% include 'blog/base/pagination_base.html' %}
{% endblock content %}
    
    

blog/templates/blog/post_edit.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    {% if post %}
        Edit - {{post.title}}
    {% else %}
        New Post
    {% endif %}
{% endblock title %}
    
{% block content %}
<div class="form-window form-window-wide">
    <form method="POST" action="{% if post %}{% url 'blog:post_edit' post.pk %}{% else %}{% url 'blog:post_create'%}{% endif %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% if images_disabled %}
            <div class="alert alert-warning">
                Image uploading is currently disabled
            </div>
        {% endif %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
        {% endfor %}
        <div class="mb-3">
            <label id="title" class="form-label" for="{{form.title.name}}">Title</label>
            <input type="text" class="form-control{%if form.title.errors%} is-invalid{%endif%}" name="{{form.title.name}}" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
            <div class="invalid-feedback">
                {% for error in form.title.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                <label id="header-image" class="form-label" for="{{form.header_image.name}}">Header Image</label>
                <input type="file" class="form-control{%if form.header_image.errors%} is-invalid{%endif%}" name="{{form.header_image.name}}" accept="image/*" {% if images_disabled %}disabled{% endif %}>
                {% if post and post.get_header_image_file_name %}
                    <div class="form-text">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="remove-header-image" name="{{form.remove_header_image.name}}">
                            <label class="form-check-label" for="remove-header-image">
                                Remove header image ({{post.get_header_image_file_name}})
                            </label>
                        </div>
                    </div>
                {% endif %}
                <div class="invalid-feedback">
                    {% for error in form.header_image.errors %}
                        <div>{{error}}</div>
                    {% endfor %}
                </div>
            </div>
            <div class="col">
                <label id="tags" class="form-label" for="{{form.tags.name}}">Tags</label>
                <input type="text" class="form-control{%if form.tags.errors%} is-invalid{%endif%}" name="{{form.tags.name}}" value="{% if form.tags.value %}{{ form.tags.value }}{% endif %}">
                <div class="form-text">A comma seperated list of tags</div>
                <div class="invalid-feedback">
                    {% for error in form.tags.errors %}
                        <div>{{error}}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
        
        <div class="mb-3">
            <label class="form-label" for="content">Post Contents</label>
            <textarea id="content" rows="10" class="form-control{%if form.content.errors%} is-invalid{%endif%} markdown-editor" aria-label="With textarea" name="{{form.content.name}}">{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>
            <div class="form-text">Format with markdown</div>
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        
        <div class="mb-2">
            <div id="content-preview" class="border p-2"></div>
        </div>
        <div class="clearfix">
            <button type="submit" class="btn btn-primary float-end">{% if post %}Save{% else %}Post{% endif %}</button>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/tag_detail.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    {{tag.name}}
{% endblock title %}

{% block content %}
    <div class="">
        <div class="mb-2 mt-2">
            <h3 class="d-inline">{{tag.name}}</h3>
        </div>
        
    </div>
    {% include 'blog/base/post_list_base.html' %}
{% endblock content %}

blog/templates/blog/tag_list.html
{% extends 'blog/base/page_base.html' %}
{% load blog_tags %}

{% block title %}
    Tags
{% endblock title %}

{% block content %}
    <div class="mt-2 clearfix">
        <h3 class="d-inline mt-2">Tags</h3>
        <span class="user-controls float-end">
            <div class="btn-group">
                <a href="{% current_url 'sort' 'most_posts' %}" class="btn btn-primary{% if sort_by == 'most_posts' %} active {% endif %}" aria-current="page">Most Posts</a>
                <a href="{% current_url 'sort' 'least_posts' %}" class="btn btn-primary{% if sort_by == 'least_posts' %} active {% endif %}" aria-current="page">Least Posts</a>
                <a href="{% current_url 'sort' 'name' %}" class="btn btn-primary{% if sort_by == 'name' %} active {% endif %}" aria-current="page">A-Z</a>
              </div>
        </span>
    </div>
    <div class="tags-list mt-2">
        {% for tag in tag_list %}
            <div class="tags-list-item">
                <a href="{% url 'blog:tag_detail' tag.slug %}">{{ tag }}</a>
                ({{ tag.post_set.all.count }})
            </div>
        {% empty %}
            <div class="text-muted text-center mt-2">No tags found</div>
        {% endfor %}
    </div>
    {% include 'blog/base/pagination_base.html' %}
{% endblock content %}

blog/templates/blog/user_detail.html
{% extends 'blog/base/page_base.html' %}
{% load blog_filters %}
{% block title %}
    {{ profile_user.username }} - Profile
{% endblock title %}

{% block content %}
    <div class="clearfix mb-2 mt-2">
        <h3 class="d-inline">{{profile_user.username}}</h3>
        <span class="user-controls float-end">
            {% if user|can_edit:profile_user.author %}
                    <a class="btn btn-primary" href="{% url 'blog:user_edit' profile_user.author.slug %}">Edit</a>
            {% endif %}
            {% if user.is_authenticated and profile_user != user %}
                <a class="btn btn-primary" href="{% url 'notifications:privatemessage_user_detail' profile_user.id %}">Message</a>
            {% endif %}
            {% if profile_user.author.visible %}
                <a class="btn btn-primary" href="{% url 'blog:author_detail' profile_user.author.slug %}">View blog</a>
            {% endif %}
        </span>
    </div>
    <ul class='comments-list'>
        {% if comments %}
            {% for comment in comments %}
                {% include 'blog/base/comment_base.html'%}
            {% endfor %}
        {% else %}
            <div class="text-muted text-center">User hasn't left any comments</div>
        {% endif %} 
    </ul>
    {% include 'blog/base/pagination_base.html' %}
{% endblock content %}

blog/templates/blog/user_edit.html
{% extends 'blog/base/page_base.html' %}
{% load blog_filters %}

{% block title %}
    {% if author.user == user %}
        Settings
    {% else %}
        {{ author.user.username }} - Settings
    {% endif %}
{% endblock title %}
    
{% block content %}
<div class="form-window">
    {% if saved %}
    <div class="alert alert-success" role="alert">
        Settings Saved!
    </div>
    {% endif %}
    <form method="post" action="{% url 'blog:user_edit' slug=author.slug%}">
        {% csrf_token %}
        {% for error in user_form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
        {% endfor %}
        {% for error in author_form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
        {% endfor %}
        {% if can_edit_author %}
        <h3>Blog Settings</h3>
        <div class="mb-3">
            <label id="bio" class="form-label" for="{{author_form.bio.name}}">Bio</label>
            <textarea rows="10" class="form-control{%if author_form.bio.errors%} is-invalid{%endif%}" aria-label="With textarea" name="{{author_form.bio.name}}">{% if author_form.bio.value %}{{ author_form.bio.value }}{% endif %}</textarea>
            <div class="invalid-feedback">
                {% for error in author_form.bio.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        {% if user|can_edit:author and author.user != request.user %}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" {% if author_form.author_enabled.value %}checked{% endif %} id="author-enabled" name="{{author_form.author_enabled.name}}">
                <label class="form-check-label" for="{{author_form.author_enabled.name}}">
                    Make this user a blog author
                </label>
            </div>
        {%endif%}
        {% if user.is_staff and author.user != request.user %}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" {% if author_form.moderator.value %}checked{% endif %} id="moderator" name="{{author_form.moderator.name}}">
                <label class="form-check-label" for="{{author_form.moderator.name}}">
                    Allow this user change other users author status
                </label>
            </div>
        {%endif%}
        {% endif %}
        {% if can_edit_user %}
        <h3>Security Settings</h3>
        <div class="mb-3">
            <label id="current-password" class="form-label" for="{{user_form.current_password.name}}">Current Password</label>
            <input type="password" class="form-control{%if user_form.current_password.errors%} is-invalid{%endif%}" name="{{user_form.current_password.name}}">
            <div class="form-text">Required to change your email or password</div>
            <div class="invalid-feedback">
                {% for error in user_form.current_password.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3">
            <label id="email" class="form-label" for="{{user_form.email.name}}">Email</label>
            <input type="email" class="form-control{%if user_form.email.errors%} is-invalid{%endif%}" name="{{user_form.email.name}}" value="{% if user_form.email.value %}{{ user_form.email.value }}{% endif %}">
            <div class="invalid-feedback">
                {% for error in user_form.email.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3">
            <label id="password" class="form-label" for="{{user_form.password.name}}">New Password</label>
            <input type="password" class="form-control{%if user_form.password.errors%} is-invalid{%endif%}" name="{{user_form.password.name}}">
            <div class="invalid-feedback">
                {% for error in user_form.password.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        <div class="mb-3">
            <label id="confirm-password" class="form-label" for="{{user_form.confirm_password.name}}">Confirm New Password</label>
            <input type="password" class="form-control{%if user_form.confirm_password.errors%} is-invalid{%endif%}" name="{{user_form.confirm_password.name}}">
            <div class="invalid-feedback">
                {% for error in user_form.confirm_password.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        
        {% endif %}
        <div class="clearfix">
            {% if user|can_delete:author %}
                <a href="{% url 'blog:user_delete' author.slug %}?prev={{ request.get_full_path }}" class="btn btn-danger float-start">Delete</a>
            {% endif %}
            <button type="submit" class="btn btn-primary float-end">Apply</button>
        </div>
    </form>
</div>
{% endblock content %}
    