blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('posts/', views.PostIndexView.as_view(), name='post_index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/create', views.post_edit_view, name='post_create'),
    path('posts/<int:pk>/edit', views.post_edit_view, name='post_edit'),
    path('posts/<int:pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:pk>/comments', views.PostCommentIndexView.as_view(), name='post_comment_index'),
    path('posts/<int:pk>/comments/new', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<int:pk>/edit', views.CommentEditView.as_view(), name='comment_edit'),
    path('comments/<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comments/<int:pk>/vote', views.comment_vote, name='comment_vote'),
    path('authors/<slug:slug>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('users/<slug:slug>/edit', views.user_edit_view, name='user_edit'),
    path('users/<slug:slug>/delete', views.UserDeleteView.as_view(), name='user_delete'),
    path('users/<slug:slug>/', views.UserDetailView.as_view(), name='user_detail'),
    #path('notifications/', views.NotificationIndexView.as_view(), name='notification_index'),
   # path('notifications/<int:pk>/delete', views.NotificationDeleteView.as_view(), name='notification_delete'),
    path('tags/', views.TagIndexView.as_view(), name='tag_index'),
    path('tags/<slug:slug>/', views.TagDetailView.as_view(), name='tag_detail'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('notifications/', include('notifications.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='/blog/posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifications/urls.py
from django.urls import path
from . import views

app_name='notifications'
urlpatterns = [
    path('', views.NotificationIndexView.as_view(), name='notification_index'),
    path('<int:pk>/delete', views.NotificationDeleteView.as_view(), name='notification_delete'),
    path('messages/', views.PrivateMessageIndexView.as_view(), name='privatemessage_index'),
    path('messages/<int:pk>', views.PrivateMessageUserDetailView.as_view(), name='privatemessage_user_detail'),
    path('messages/system', views.PrivateMessageUserDetailView.as_view(), name='privatemessage_system_detail'),
    path('messages/<int:pk>/create', views.PrivateMessageCreateView.as_view(), name='privatemessage_create'),
    path('messages/<int:pk>/delete', views.PrivateMessageDeleteView.as_view(), name='privatemessage_delete'),
]

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.conf import settings
from .models import Author, Post
from PIL import Image
from django.contrib.humanize.templatetags.humanize import intcomma
from accounts.forms import BaseUserForm
from django.utils.translation import gettext as _

class UserSettingsForm(BaseUserForm):
    password = forms.CharField(max_length=User.password.field.max_length, required=False)
    confirm_password = forms.CharField(max_length=User.password.field.max_length, required=False)
    current_password = forms.CharField(max_length=User.password.field.max_length, required=False)
    
    def __init__(self, *args, **kwargs):
        if not 'user' in kwargs:
            raise AttributeError('User cannot be None')
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']

    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        current_password = self.cleaned_data.get('current_password')
        email = self.cleaned_data.get('email')

        if password or email != self.user.email:
            if not current_password:
                self.add_error('current_password', _('Required to change username or password'))
            elif not authenticate(username=self.user.username, password=current_password):
                self.add_error('current_password', _('Password is incorrect'))

class AuthorSettingsForm(forms.ModelForm):
    author_enabled = forms.BooleanField(required=False)
    moderator = forms.BooleanField(required=False)

    class Meta:
        model = Author
        fields = ['bio']

class PostForm(forms.ModelForm):
    tags = forms.CharField(max_length=255, required=False)
    remove_header_image = forms.BooleanField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'header_image', 'content']

    def clean(self):
        super().clean()
        header_image_file = self.cleaned_data.get('header_image')
        if header_image_file:
            with Image.open(header_image_file) as im:
                total_pixels = im.width * im.height
                if total_pixels > 40000000:
                    self.add_error('header_image', f'Image size ({intcomma(total_pixels)} pixels) exceeds limit of 10,000,000 pixels')

blog/views.py
from django.contrib.auth.models import User
from notifications.models import NotificationType
from django.http.response import HttpResponseRedirect, JsonResponse
from django.http import Http404
from django.urls.base import reverse
from blog.forms import AuthorSettingsForm, UserSettingsForm, PostForm
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from django.views import View
from .models import Post, Author, Comment, Tag
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.template.defaultfilters import slugify
from PIL import Image
from os.path import join, exists
from os import remove
from django.db.models import Count, F, Q
from .templatetags.blog_filters import compact_int
from django.contrib.auth.password_validation import password_changed
from django.conf import settings
# Create your views here.

class PostIndexView(ListView):
    model = Post
    paginate_by = 20
    queryset = Post.objects.filter(author__visible=True)

class PostDetailView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk, author__visible=True)
        comments = post.comment_set.order_by('-votes')[:5]
        return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'comment_count': post.comment_set.count()})

class PostCommentIndexView(ListView):
    paginate_by = 20
    template_name = 'blog/post_comment_index.html'
    context_object_name = 'comments'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['post'] = self.post
        context['sort_by'] = self.sort_by
        return context

    def get_queryset(self):
        self.post = get_object_or_404(Post, pk=self.kwargs['pk'], author__visible=True)
        self.sort_by = 'top'
        if 'sort' in self.request.GET:
            sort = self.request.GET['sort']
            if sort == 'recent':
                self.sort_by = 'recent'
                return self.post.comment_set.order_by('-created_on').all()
        return self.post.comment_set.order_by('-votes')

class AuthorDetailView(ListView):
    paginate_by = 20
    template_name = 'blog/author_detail.html'

    def get_queryset(self):
        self.author = get_object_or_404(Author.objects.filter(visible=True), slug=self.kwargs['slug'])
        return self.author.post_set.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        return context

#TODO Only check user_form.isvalid() if can_user_edit is true
@login_required
def user_edit_view(request, slug):
    
    author = get_object_or_404(Author, slug=slug)
    can_edit_user = request.user == author.user
    can_edit_author = author.can_user_edit(request.user)
    saved = False
    if not can_edit_user and not can_edit_author:
        raise PermissionDenied
    if request.method == 'POST':
        user_form = UserSettingsForm(request.POST, user=author.user)
        author_form = AuthorSettingsForm(request.POST)
        if user_form.is_valid() and author_form.is_valid():
            saved = True
            password = user_form.cleaned_data.get('password')
            email = user_form.cleaned_data.get('email')
            if can_edit_user:
                author.user.email = email
                if password:
                    author.user.set_password(password)
                    password_changed(password, user=author.user)
            if can_edit_author:
                author.bio = author_form.cleaned_data.get('bio')

                if author.user != request.user:
                    author.set_author(author_form.cleaned_data['author_enabled'])
                    
                if author.user != request.user and request.user.is_staff:
                    author.set_moderator(author_form.cleaned_data['moderator'])
                author.save()
            author.user.save()
            
            if request.user == author.user:
                login(request, author.user) #Changing a users password logs them out   
    else:
       user_form = UserSettingsForm(user=author.user, initial={'email': author.user.email})
       author_form = AuthorSettingsForm(initial={'author_enabled': author.visible, 'moderator': author.user.has_perm('blog.edit_author'), 'bio': author.bio})

    context = {
        'user_form': user_form, 
        'author_form': author_form, 
        'author': author, 
        'saved': saved,
        'can_edit_author': can_edit_author,
        'can_edit_user': can_edit_user,
    }

    return render(request, 'blog/user_edit.html', context)

@login_required
def post_edit_view(request, pk=None):
    post = get_object_or_404(Post, pk=pk, author__visible=True) if pk else None
    if (post and not post.can_user_edit(request.user)) or (not post and not Post.can_user_create(request.user)):
        raise PermissionDenied
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            if not post:
                post = Post(author=request.user.author)
            post.title = form.cleaned_data.get('title')
            post.content = form.cleaned_data.get('content')
            post.save()
            header_image = form.cleaned_data.get('header_image')
            if header_image and not getattr(settings, 'DISABLE_IMAGE_UPLOADS', False):
                
                post.header_image_name = header_image.name
                with Image.open(header_image) as im:
                    post.header_image = join(Post.header_image.field.upload_to, f'header_image_post_{post.pk}.jpeg')
                    image = Image.new('RGB', (im.width, im.height))
                    image.putdata(im.getdata())
                    image.save(post.header_image.path)
                    post.save()
            elif form.cleaned_data.get('remove_header_image', False):
                if exists(post.header_image.path):
                    remove(post.header_image.path)
                post.header_image = None
                post.header_image_name = None
                post.save()

            post.tags.clear()
            for tag_name in form.cleaned_data.get('tags', '').lower().split(','):
                if tag_name.strip():
                    try:
                        tag = Tag.objects.get(slug=slugify(tag_name.strip()))
                    except Tag.DoesNotExist:
                        tag = Tag()
                    tag.name = tag_name.strip()
                    tag.save()
                    post.tags.add(tag)
            post.save()
            return HttpResponseRedirect(reverse('blog:post_detail', kwargs={'pk': post.pk}))
    else:
        form = PostForm(instance=post, initial={'tags': post.tags_str() if post else ''})
    return render(request, 'blog/post_edit.html', {'form': form, 'post': post, 'images_disabled': getattr(settings, 'DISABLE_IMAGE_UPLOADS', False)})

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post

    def test_func(self):
        return self.get_object().can_user_delete(self.request.user)

    def get_success_url(self, *args, **kwargs):
        return reverse('blog:author_detail', kwargs={'slug': self.get_object().author.slug})

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['text']

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        context['next'] = self.request.GET.get('next', None)
        return context

    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        comment = Comment(post=post, commenter=self.request.user, text=form.cleaned_data['text'])
        comment.save()
        if post.author.user != self.request.user:
            post.author.user.notification_set.create(content=comment, type=NotificationType.get(name='new_comment_on_post'))
        next = self.request.POST.get('next', None)
        return HttpResponseRedirect(next if next else '/')

class CommentEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['text']

    def test_func(self):
        return self.get_object().can_user_edit(self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['post'] = self.get_object().post
        context['next'] = self.request.GET.get('next', None)
        return context

    def form_valid(self, form):
        comment = self.get_object()
        comment.text=form.cleaned_data['text']
        comment.save()
        next = self.request.POST.get('next', None)
        return HttpResponseRedirect(next if next else '/')

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next', None)
        return context

    def test_func(self):
        return self.get_object().can_user_delete(self.request.user)

    def get_success_url(self, *args, **kwargs):
        next = self.request.POST.get('next', None)
        return next if next else '/'

class UserDetailView(ListView):
    paginate_by = 20
    template_name = 'blog/user_detail.html'
    context_object_name = 'comments'

    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['profile_user'] = self.user
        return context

    def get_queryset(self):

blog/templates/notifications/privatemessage_confirm_delete.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    Delete - {{privatemessage.text}}
{% endblock title %}

{% block content %}
    <div class="post-container">
        <div class="post-content">
            <div>
                <h4>Delete message to {{privatemessage.get_receiver_name}}</h4>
                <div>{{privatemessage.text}}</div>
            </div>
        </div>
        <div>
            <div>
                <span class="float-end">
                    <form method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Delete">
                        <input type="hidden" name="next" value="{{ next }}">
                        <a class="btn btn-primary" href="{{ privatemessage.get_receiver_messages_url }}">Cancel</a>
                    </form>
                </span>
            </div>   
        </div>
    </div> 
{% endblock content %}

blog/templates/notifications/privatemessage_form.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    New private message
{% endblock title %}

{% block content %}
    <div class='mt-2'>
        <h3>Message {{profile_user.username}}</h3>
    </div>
    
    <form method="POST" action="{% url 'notifications:privatemessage_create' profile_user.id %}">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">{{error}}</div>
        {% endfor %}
        <div class="mb-3">
            <label id="content" class="form-label" for="{{form.text.name}}">Message text</label>
            <textarea rows="2" class="form-control{%if form.text.errors%} is-invalid{%endif%}" aria-label="With textarea" name="{{form.text.name}}">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
            <div class="invalid-feedback">
                {% for error in form.text.errors %}
                    <div>{{error}}</div>
                {% endfor %}
            </div>
        </div>
        <div>
            <button type="submit" class="btn btn-primary float-end">Send</button>
        </div>
    </form>
{% endblock content %}

blog/templates/notifications/privatemessage_index.html
{% extends 'blog/base/page_base.html' %}
{% load blog_tags %}

{% block title %}
    Private Messages
{% endblock title %}

{% block content %}
    <div class="mt-2 clearfix">
        <h3 class="d-inline">Messages</h3>
        <form class="d-flex d-inline float-end" method="GET">
            <input class="form-control me-2" type="search" placeholder="Search messages" aria-label="Search" name="search" value="{{ search }}">
            <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>
    </div>
    <div class="messages-container mt-2">

        {% if privatemessage_list %}
            <ul class="list-group">
                {% for message in privatemessage_list %}
                    <li class="list-group-item">
                        <div class="clearfix">
                            <a href="{{ message.get_sender_messages_url }}">Sent by {{message.get_sender_name}}</a> 
                            <span class="float-end text-muted">
                                {{message.created_on|timesince}} ago
                            </span>
                        </div>
                        <div>
                            {% markdown message.text %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <div class="text-muted text-center">No messages</div>
        {% endif %}
    </div>
    <div class="mt-2">
        {% include 'blog/base/pagination_base.html' %}
    </div>
{% endblock content %}

blog/templates/notifications/privatemessage_notification_inline.html
{% load blog_tags %}
<div>
    <div class="comment-notification{% if not notification.seen %} comment-notification-unseen{% endif %}">
        <a href="{{ privatemessage.get_sender_messages_url }}">New message from {{privatemessage.get_sender_name}}</a>
        <span class="float-end text-muted">
            {{notification.created_on|timesince}} ago
            <form class="d-inline" method="POST" action="{% url 'notifications:notification_delete' notification.id %}">
                {% csrf_token %}
                <button type="submit" title="Dismiss" class="btn-blank"><i class="bi bi-x-lg ms-2"></i></button>
            </form>
        </span>
    </div>
    <div>{% markdown privatemessage.text %}</div>
</div>

blog/templates/notifications/privatemessage_user_detail.html
{% extends 'blog/base/page_base.html' %}
{% load blog_tags %}

{% block title %}
    {% if profile_user %}
        {{profile_user.username}} - Messages
    {% else %}
        system - Messages
    {% endif %}
{% endblock title %}

{% block content %}

    <div class="clearfix mb-2 mt-2">
        <h3 class="d-inline">
            Messages with 
            {% if profile_user %}
                {{profile_user.username}}
            {% else %}
                system
            {% endif %}
        </h3>
        <span class="user-controls float-end">
            {% if profile_user %}
                <a class="btn btn-primary" href="{% url 'blog:user_detail' profile_user.author.slug %}">View profile</a>
            {% endif %}  
        </span>
    </div>
    
    <div class="border p-2">
        {% if privatemessage_list %}
            {% for message in privatemessage_list reversed %}
                <div class="clearfix">
                    <div class="message{% if message.sender == user %} message-sent{% else %} message-reply{% endif %}">
                        <div class="clearfix">
                            <span class="text-muted message-header">
                                {{message.created_on|timesince}} ago
                                {% if message.sender == user %}
                                    <a href="{% url 'notifications:privatemessage_delete' message.id %}?next={{ request.get_full_path }}" title="Delete"><i class="bi bi-trash ms-2 link-icon-btn"></i></a>
                                {% endif %}
                            </span>
                        </div>
                        <div class="message-body border p-1 m-1">{% markdown message.text %}</div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="text-muted text-center">No messages yet.</div>
        {% endif %}
    </div>
    {% if profile_user %}
        <form class="mt-3" method="POST" action="{% url 'notifications:privatemessage_create' profile_user.id %}">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label" for="content">Message text</label>
                <textarea id="content" rows="2" class="form-control markdown-editor" aria-label="With textarea" name="text"></textarea>
                <div class="form-text">Format with markdown</div>
            </div>
            <div>
                <button type="submit" class="btn btn-primary float-end">Send</button>
            </div>
            <div class="mb-2">
                <div id="content-preview" class="border p-2"></div>
            </div>
        </form>
    {% endif %}
    <div class="mt-2">
        {% include 'blog/base/pagination_base.html' %}
    </div>
{% endblock content %}

blog/templates/notifications/privatemessage_user_list.html
{% extends 'blog/base/page_base.html' %}

{% block title %}
    Private Messages
{% endblock title %}

{% block content %}

    <div class='mt-2'>
        {% if profile_user %}
            <h3>{{profile_user.username}}</h3>
        {% else %}
            system
        {% endif %}
    </div>
    
    <div class="border p-2">
        {% if privatemessage_list %}
            {% for message in privatemessage_list reversed %}
                <div class="clearfix">
                    <div class="message{% if message.sender == user %} message-sent{% else %} message-reply{% endif %}">
                        <div class="clearfix">
                            <span class="text-muted message-header">{{message.created_on|timesince}} ago</span>
                        </div>
                        <div class="message-body border p-1 m-1">{{message.text}}</div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="text-muted text-center">No messages yet.</div>
        {% endif %}
    </div>
    {% if profile_user %}
        <form class="mt-3" method="POST" action="{% url 'notifications:privatemessage_create' profile_user.id %}">
            {% csrf_token %}
            <div class="mb-3">
                <label id="content" class="form-label" for="text">Message text</label>
                <textarea rows="2" class="form-control" aria-label="With textarea" name="text"></textarea>
            </div>
            <div>
                <button type="submit" class="btn btn-primary float-end">Send</button>
            </div>
        </form>
    {% endif %}
    <div class="mt-2">
        {% include 'blog/base/pagination_base.html' %}
    </div>
{% endblock content %}